### ISSUE TITLE
A0V3R Wargame 플래그 가려주세요.

### ISSUE THREAD

**Issue by jeongjy0317** [JunhoYeo/WriteUps#7]
공정한 실력경쟁의 장 형성 위해 플래그를 공유하지 말아주세요.
자세한 사항은 [A0V3R Wargame 주의사항](https://wargame.aover.team/precautions)을 참고하세요.

**Comment by junhoyeo** [comment]
afd2e4cc514cf5b82097acc5b35c55cfc99bf937 에서 반영했습니다.
